#!/usr/bin/env ruby

require "bundler/setup"
require "provisional"
require "gli"


include GLI::App
subcommand_option_handling :normal
arguments :strict


program_desc "Manage and provision server images"
version Provisional::VERSION


exit run(ARGV)
